baseURL = "https://suyashsrijan.com/blog/"
languageCode = "en-gb"
title = "Suyash's blog"
theme = "archie"
copyright = "Â© Suyash Srijan"

[params]
  mode = "toggle"
  useCDN = false
  subtitle = "Thoughts on code and other curiosities"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      footnote = true
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    style = 'base16-snazzy'